import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import styles from "../../styles/Home.module.css";

import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.homepageBackGround}>
      <Head>
        <title>Marcin Wozniak - Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="min-h-[95vh]">
        <div className="flex justify-center items-center min-h-[70vh]">
          <div className="container flex">
            <div className="flex flex-col">
              <h1 className="text-6xl font-bold">
                Full Stack JavaScript <br /> Software Engineer
              </h1>
              <div className="flex gap-10 flex-row">
                <div className="flex flex-col gap-10">
                  <div className={styles.hireButton}>Hire</div>
                  <div className={styles.contactButton}>Contact</div>
                </div>
                <div>
                  <div className={styles.linkedinButton}>LinkedIn</div>
                </div>
              </div>
            </div>
            <div></div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
